name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate
        run: |
          curl -L https://github.com/tatthien/giraffe/releases/download/v0.12.0/giraffe_0.12.0_linux_amd64.tar.gz | tar xvz
          ./giraffe

      - name: Deploy
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "./dist"
          production-deploy: true
          netlify-config-path: ./netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
